name: "build and test"
on:
  pull_request:
    branches: 
      - master
      - dev
      - develop
  push:
    branches: 
      - master
      - dev
      - develop
jobs:
  build-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: Build All
      run: .\build-all-release.ps1
      working-directory: .\build
      shell: powershell

    - name: Test All
      run: .\test-all.ps1
      working-directory: .\build
      shell: powershell
    
    - name: Pack All
      run: .\pack-all.ps1
      working-directory: .\build
      shell: powershell
